name: Secret Scanning
on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: GitGuardian/gg-shield-action@master
      with:
        api_key: ${{ secrets.GITGUARDIAN_API_KEY }} 